### ISSUE TITLE
import NUMPY.pyd error

### ISSUE THREAD

**Issue by Scheaven** [lxlscut/Parallax_tolerant_Image_Stitching#1]
Can you provide the source code to generate NUMPY. Pyd?
The file cannot be loaded on Linux

**Comment by lxlscut** [comment]
https://github.com/lxlscut/warp
this is the project of generating the pyd file.
and u could find all the pyd in my project in my account.
btw,there are still some problems about this project,i guess is about the maxflow. hope u could give some suggestions and make this project better.  thanks!

**Comment by the-cat-crying** [comment]
Can pyd be written in Python?
